version: 1
update_configs:
  # Keep Dockerfile up to date, batching pull requests weekly
  - package_manager: 'python'
    directory: '{{cookiecutter.project_slug}}/backend'
    update_schedule: 'monthly'
